baseURL: 'https://www.niksa.dev'
title: Niksa's Notes
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

minify:
  disableXML: true
  minifyOutput: true

params:
  profileMode:
    enabled: true # needs to be explicitly set
    title: Niksa's Notes
    # imageUrl: '<img location>'
    # imageTitle: my image
    buttons:
      - name: Posts
        url: posts
      - name: Tags
        url: tags
      #- name: Archives
      #  url: archives
      - name: About
        url: about

  socialIcons:
    - name: github
      url: 'https://github.com/miniksa'
    - name: email
      url: 'mailto:<FIRSTNAME>.<LASTNAME>@outlook.com'
